# Generated by Django 4.2.2 on 2023-06-22 13:39

from django.db import migrations, models
import files


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Outcomes_achieved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to=files.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_video',
            field=models.ImageField(blank=True, null=True, upload_to=files.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='project_gallery',
            name='project_img',
            field=models.ImageField(blank=True, null=True, upload_to=files.FileUpload.upload_to),
        ),
        migrations.AddField(
            model_name='project',
            name='objective',
            field=models.ManyToManyField(blank=True, to='project.objective'),
        ),
        migrations.AddField(
            model_name='project',
            name='outcomes_achieved',
            field=models.ManyToManyField(blank=True, to='project.outcomes_achieved'),
        ),
        migrations.AddField(
            model_name='project',
            name='your_role_project',
            field=models.ManyToManyField(blank=True, to='project.role_project'),
        ),
    ]
