# Generated by Django 4.2.2 on 2023-07-03 02:44

from django.db import migrations, models
import files


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_short_description_alter_project_main_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to=files.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_video',
            field=models.ImageField(blank=True, null=True, upload_to=files.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='project_gallery',
            name='project_img',
            field=models.ImageField(blank=True, null=True, upload_to=files.FileUpload.upload_to),
        ),
    ]
