# Generated by Django 4.1.4 on 2023-08-10 20:33

from django.db import migrations, models
import files


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_project_main_img_alter_project_main_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to=files.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_video',
            field=models.ImageField(blank=True, null=True, upload_to=files.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='project_gallery',
            name='project_img',
            field=models.ImageField(blank=True, null=True, upload_to=files.FileUpload.upload_to),
        ),
    ]
