# Generated by Django 4.2.2 on 2023-06-22 13:38

from django.db import migrations, models
import django.db.models.deletion
import faicon.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=30, null=True, unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('percent', models.PositiveIntegerField()),
                ('icon', faicon.fields.FAIconField(max_length=50)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=30, null=True, unique=True, verbose_name='slug')),
                ('skill_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_of_group', to='skill.skillgroup')),
            ],
        ),
    ]
