# Generated by Django 4.2.2 on 2023-07-03 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='skillgroup',
            name='slug',
        ),
    ]
