# Generated by Django 4.1.4 on 2023-08-10 21:05

from django.db import migrations, models
import files


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_introduction_cv_alter_introduction_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gitHub', models.CharField(max_length=100)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='introduction',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=files.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=files.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to=files.FileUpload.upload_to),
        ),
    ]
